# Generated by Django 3.1.5 on 2021-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='ram_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Об'єм оперативної пам'яті"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='rom_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Об'єм пам'яті"),
            preserve_default=False,
        ),
    ]
