# Generated by Django 3.1.5 on 2021-01-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210119_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='fk',
        ),
    ]
